### PR TITLE
Add variable to specify path to bookmarks database

### PR DESCRIPTION
**Pull request by idmyn**
I like to keep my `bookmarks.db` file in dropbox, and this way I don't need a symlink :)

Thanks for writing this package in the first place, by the way. It's great!

### CODE REVIEW

**Comment by flexibeast** [comment]
Thank you for your kind words, and for your contribution!

i'd certainly like to support this functionality, and i've actually already got some code to do so, but i'm concerned that the `--db` option is [an undocumented API](https://github.com/jarun/buku/blob/3fc4d164d492bb87aa929d3503cdf98bb7ac7e74/buku#L4973). So i've just opened [an issue](https://github.com/jarun/buku/issues/444) asking @jarun about that option's status.

**Comment by flexibeast** [comment]
i've just pushed my own implementation to `master`, https://github.com/flexibeast/ebuku/commit/4968c19113f7b4ed197059c63bb1711abc35c412, which works for me - can you please check it works for you also?

**Comment by idmyn** [comment]
Yeah, that works for me too — and the defaults look great! Thanks again for your work on this :)

**Comment by flexibeast** [comment]
Great. :-) Thanks!

**Pull request closed without merging**
